Coders-Evoke-Community/CodersEvoke_website

assets/css/style.css
index.html
js/script.js

Hi,
The following changes have  been done
- creating of navbar using flex box
- responsive for mobile view
closes #6

navigation Bar update

---

README.md

I have updated the README.md file and edited the use of #'s.

Updated README as per Markdown rules.

---

README.md

#15  Fixed 
Added Project tree in readme.md file .

Repository structure tree added in Readme file

---

LICENSE
README.md

adding license

---

README.md

added note

---

README.md

added rohans repo and my repo for contributions

repo added

---

.github/labels.json
.github/workflows/labels.yml

added labels

---

assets/css/style.css
index.html

#28 
Heyy , I have made some changes in navbar for imporvements .

Changes made in navbar

---

README.md

Linked contributer.md to readme file
Fixes #53 
* Text-editors used: Visual Studio code

Linked contributer.md to readme file

---

assets/css/style.css
index.html

I added bottom to up scroll button for convenience of users.
Fixes #52 
* Text-editors used: Visual Studio Code

Bottom-to-top-scroll-button-added

---

404 Page/404style.css
404Page.html

Added a simple 404 page and styled it using CSS and added a button to redirect to home page.
#60
Added a 404 page and a button in the page to allow user to redirect to the landing home page.
* Text-editors used: VS Code

Add 404 Page

---

assets/css/style.css
index.html

Added Footer successfully 
Fixes #45  
Added new feature to the footer
* Text-editors used: VS-Code

Added Footer

---

assets/css/style.css

added padding in navbar

---

assets/css/style.css
index.html

added some more point in nav

---

index.html

solved bug in image

---

assets/css/style.css
index.html

Fixes the responsive issues on the home page. 
Note that these changes only reflect on mobile devices (I.e devices with screen width below 600px) We will have to check and fix the responsive issues on devices in the range 600-900px  which are mostly tablets.
#57 
Before the fix /unresponsive page.
After the fix/ responsive page

Fixing Responsive issue on homepage

---

index.html

Correcting the spelling of _Opportunities_ in the navbar
#86

Fixing the spelling mistake in navbar

---

.github/config.yml

config updated

---

README.md

Created and added the Admin section to the README.md file of this repository.
Fixes #89

Added Admin Section

---

README.md

Added a Mentor Section and centered the Admin Section  
#99

Added Mentor Section and Centered the Admin Section

---

assets/css/event.css
assets/css/style.css
contact.html
events.html
index.html

Added contents on event page. 
And changed the links of events page in navbar to redirect to events page from all the other pages.
Fixes #82 
* Version:
As shown in slack

Events Page update

---

assets/css/style.css

Fixed Horizontal Scrollbar

---

assets/css/contact.css
contact.html
js/contact.js

Added contact form backend uses JavaScript Library EmailJS. If anyone submits the contact form will send those data to mails using EmailJS to admin.
Also added the required fields so that no one can submit blank form.
Fixes #103

Added Contact Form Backend

---

events.html

Added Logo of Coders Evoke on Event Page
Fixes #113 
* Version: Windows 10
* Text-editors used: VS Code

Added Logo on Event Page

---

assets/css/style.css
index.html

added new feature of floating ball in issue #111

---

assets/css/style.css
index.html

Revert "added new feature of floating ball in issue #111"

---

assets/css/event.css
index.html

This will fix #119 #114 
Previously footer anchor links are looking like this:
After adding text-decoration: none, giving some padding and  changing the background to same as navbar:
Previously events cards have not hover effects:
After implementing hover effects and some box-shadow to make cards attractive:

Modified footer and Events cards

---

assets/css/contact.css

Changed  hover effect in contact us page Navbar
Fixes #112 
* Version: 10
* Text-editors used: VS code

Changed hover effect in contact us page navbar from blur to same as in home page

---

assets/css/event.css
assets/css/style.css
events.html
index.html

This will fix #129 
Previously:
After Fixing:

Fixed logo hover effect

---

contact.html

fix: stretchy image

---

about.html
assets/css/about.css
assets/css/contact.css
assets/css/style.css
contact.html
events.html
index.html

This will fix #133 #132 #134 
Before :
After modifying:
Demo about us Page:

Added about us and fixed logo on contact & event

---

assets/css/contact.css
contact.html

fix: Issue in contact us page

---

assets/css/style.css

Enhanced Hover Effect on cards present in events page
Fixes #114 
* Version: 10
* Text-editors used: VSCode

Enhanced hover effect on cards present in event page

---

assets/css/style.css

Fixes #145 
* Operating system: windows 
* Version: 10
* Text-editors used: Vscode

adjusted the border Radius

---

contact.html
events.html

This will solve #151 
Earlier:
After giving footer :

Given footers to events & contact 

---

Mousemove-Background/index.html
about.html
contact.html
events.html
index.html
opportunity.html
team.html

fixed issue #152
I fixed the navbar in index.html and oppertunity.html
and format document also. so now it looks good.

fix navbar button

---

contact.html

This will fix #170 
Before :
After Fixing

Fixed contact page

---

about.html
contact.html
opportunity.html

I added coder evoke Favicon in about us, contact us , opportunities page. I add all three favicon link in available in index page
I fixed 138 issue number 
* Operating system: Window 10
* Version:  20H
* Text-editors used: VS Code

Add favicon in pages other then index

---

events.html
index.html
js/script.js

Solved issue #165. Added AOS features to home and event page. That feature needed [AOS libraby](https://github.com/michalsnik/aos#basic) links in the respective js file. 
Fixes #165 
* Operating system: Windows 8
* Version: 
* Text-editors used: VS Code
Added aos libraby in script and added to index.html and event.html.
[Home Page](https://user-images.githubusercontent.com/70569920/127745022-02b279c9-faae-4b36-871d-461a1d831d5a.mp4)
[Event Page](https://user-images.githubusercontent.com/70569920/127745103-29dc8d41-5ecb-4d6c-935b-cb60c8a12473.mp4)

Added AOS Feature

---

events.html
index.html
js/script.js

Reverts Coders-Evoke-Community/CodersEvoke_website#172

Revert "Added AOS Feature"

---

about.html
contact.html
events.html
opportunity.html
team.html

Added About Us page in all Page and linking all pages each other. "You can jump directly to other page from the current page." 
I fixed issue number 139 
* Operating system: Window 10
* Version: 20H
* Text-editors used: VS - Code

 Linking all Page each other and Changes in about us page

---

about.html
assets/css/about.css
contact.html
events.html
index.html
opportunity.html

This will fix #180 
Below are some changed pages:

Added evoke logo in all pages

---

assets/css/style.css

Added Custom Scroll Bar with different color on hover and not hover.
Fixes #153

Added Custom Scroll Bar

---

assets/css/event.css
assets/css/style.css
index.html

Home page fixed #176  and added the #165 issue stated features. Because #172 PR was aborted and there is no such feature till now in the project.
* Version:
Refer to PR #172

Updated index

---

.vscode/settings.json
Mousemove-Background/style.css
assets/css/about.css
assets/css/event.css
contact.html
events.html
index.html
opportunity.html
team.html

#191 
* Operating system:Windows
* Version: 10
* Text-editors used: VScode

Logo isssue fixed

---

opportunity.html

updated images

---

README.md

The Readme for the project had typos and grammar errors. This makes it look clumsy and not professional. I have fixed all such minor yet important lines.<br>
Fixes #215
* Operating system: Linux
* Version: Ubuntu 20.04
* Text-editors used: VSCode
Not sure which screenshot to add. Let me know about it maintainers

[Docs] Fixed typos and grammar in the Readme
